name: Create zip files
on: [push]
jobs:
  create-zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create git_hash
        run: echo ${{ github.sha }} | tee ./resources/git_hash

      - name: Move linux binaries
        run: |
          mkdir -p ./exclude/firmware ./exclude/lib ./exclude/tools
          mv ./resources/lib/* ./exclude/lib
          mv ./resources/tools/*linux* ./exclude/tools

      - name: Download and extract libimobiledevice_macos
        run: |
          curl -LO https://github.com/LukeZGD/iOS-OTA-Downgrader-Keys/releases/download/tools/libimobiledevice_macos.zip
          mkdir ./resources/libimobiledevice_macos
          unzip libimobiledevice_macos.zip -d ./resources/libimobiledevice_macos
          chmod +x ./resources/libimobiledevice_macos/*

      - name: Zip macos files
        run: zip -r ${{ github.event.repository.name }}_macos.zip resources/ restore.sh README.md

      - name: Move macos binaries
        run: |
          mv ./exclude/lib/* ./resources/lib
          mv ./exclude/tools/* ./resources/tools
          mv ./resources/tools/*macos* ./exclude/tools

      - name: Download and extract libimobiledevice_linux
        run: |
          mv ./resources/libimobiledevice_macos ./exclude
          curl -LO https://github.com/LukeZGD/iOS-OTA-Downgrader-Keys/releases/download/tools/libimobiledevice_linux.zip
          mkdir ./resources/libimobiledevice_linux
          unzip libimobiledevice_linux.zip -d ./resources/libimobiledevice_linux
          chmod +x ./resources/libimobiledevice_linux/*

      - name: Zip linux files
        run: zip -r ${{ github.event.repository.name }}_linux.zip resources/ restore.sh README.md

      - name: Move linux binaries and other files
        run: |
          mv ./resources/lib/* ./exclude/lib
          mv ./resources/tools/*linux* ./exclude/tools
          mv ./resources/firmware/FirmwareBundles ./resources/firmware/JailbreakBundles ./exclude/firmware

      - name: Download and extract libimobiledevice_win
        run: |
          mv ./resources/libimobiledevice_linux ./exclude
          curl -LO https://github.com/LukeZGD/iOS-OTA-Downgrader-Keys/releases/download/tools/libimobiledevice_win.zip
          mkdir ./resources/libimobiledevice_win
          unzip libimobiledevice_win.zip -d ./resources/libimobiledevice_win

      - name: Download and extract tools_win
        run: |
          curl -LO https://github.com/LukeZGD/iOS-OTA-Downgrader-Keys/releases/download/tools/tools_win.zip
          unzip tools_win.zip -d ./resources

      - name: Zip win files
        run: zip -r ${{ github.event.repository.name }}_win.zip resources/ restore.cmd restore.sh README.md

      - name: Copy exclude files back
        run: cp -r ./exclude/* ./resources

      - name: Download other files
        run: ./resources/complete.sh

      - name: Zip complete files
        run: zip -r ${{ github.event.repository.name }}_complete.zip resources/ restore.cmd restore.sh README.md

      - name: Update latest release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.event.repository.name }}_complete.zip
            ${{ github.event.repository.name }}_macos.zip
            ${{ github.event.repository.name }}_linux.zip
            ${{ github.event.repository.name }}_win.zip
